### ISSUE TITLE
The slides of ICP can't be downloaded

### ISSUE THREAD

**Issue by RebeWu** [yangyanli/Course_PR_17#122]
Why the slides of ICP can't be downloaded？

**Comment by chengluyu** [comment]
This may caused by usage of relative path instead of absolute path. Before TA fix this bug you can access the slides by [this link](http://www.cs.tau.ac.il/~dcor/Graphics/adv-slides/ICP.ppt).

**Comment by Shimingyi** [comment]
Link updated.

**Comment by chengluyu** [comment]
@Shimingyi Wow, so late, such hard-working. [doge]

**Comment by Shimingyi** [comment]
@chengluyu lol, you too, take care of your hair 🤒
